name: Manual Scraper Run

# Разрешаем push в репозиторий
permissions:
  contents: write

on:
  workflow_dispatch:
    # Запуск вручную из вкладки Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # persist-credentials = true, чтобы сохранять токен для push-операций
          persist-credentials: true

      # 2. Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запускаем скрипт
      - name: Run scraper script
        run: python script.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

      # 5. Коммитим файл previous_value.txt (если есть изменения)
      - name: Commit changes
        run: |
          # Проверяем, есть ли какие-то изменения
          if git diff --quiet; then
          echo "No changes detected. Skipping commit."
          else
          echo "Changes detected. Committing..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add previous_value.txt
          git commit -m "Update previous_value.txt"
          git push
          fi
